### ISSUE TITLE
Allow project groups to add sub project groups via UI

### ISSUE THREAD

**Issue by eanderson4** [anderson-optimization/frontend-documentation#162]
### Subject of the issue
Allow group to add a sub group via UI

**Comment by eanderson4** [comment]
The dialog for this should give the user the ability to pick out groups from both there current team and optionally any other team they are on.

This would most likely belong in the project group edit page.

**Comment by eanderson4** [comment]
Subgroups look something like this on the main group item

```
subGroups:
  <id>:
    rn: <rn>
    type: <type>
    wkt: <wkt-geo>
    name: <name>
```

where it can have many subGroup id properties representing indivual projects.  The `id` can be the project id, but it doesn't have to be.  It allows us, if we want, to make sure we don't add duplicate projects without checking the whole list.
