### ISSUE TITLE
Add company to team

### ISSUE THREAD

**Issue by eanderson4** [anderson-optimization/frontend-documentation#179]
### Subject of the issue
Companies need to be added to teams for the team filtering to work.

format of auth/team
```yaml
company:
  <company-id>:
     role: "test"
```

Role doesn't do anything at this point, the object just needs to exist
