### ISSUE TITLE
Row Groups & Values Usage Unclear

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#296]
### Subject of the issue
I am unsure how to use the row values and row groups feature. 

I've tried dragging/following the instructions, but it isn't working. 

It is likely that I am not doing this properly, but if that's the case, we should add better user feedback with these if we want them included.

**Comment by eanderson4** [comment]
oh actually i probably haven't merged configs for this

it only allows you to do groupings by ones we allow

i'll let you know when config is merged

**Comment by eanderson4** [comment]
here are some ones that should work (config is updating now)

Item - Created by

## Addresses
```
   city:
+    enableRowGroup: true
     name: City
   county:
+    enableRowGroup: true
     name: County
   owner:
+    enableRowGroup: true
     name: Owner
   state:
+    enableRowGroup: true
     name: State
   status:
+    enableRowGroup: true
     name: Status
   zip:
+    enableRowGroup: true
     name: Zip Code
```

# General
```
   city:
+    enableRowGroup: true
     name: City
   county:
+    enableRowGroup: true
     name: County
   owner:
+    enableRowGroup: true
     name: Owner
   state:
+    enableRowGroup: true
     name: State
   zip:
+    enableRowGroup: true
     name: Zip Code
```

# Land
```
   buildable-acre:
## This enables aggregation (i.e. sum buildable area for group)
+    enableValue: true
     name: Buildable Area (Acres)
   cid:
+    enableRowGroup: true
     name: County ID
   land-use-code:
+    enableRowGroup: true
     name: Land Use Code
```

# Projects
```
   completed:
+    enableRowGroup: true
     name: Project Completed
  priority:
+    enableRowGroup: true
     name: Priority
  project_stage:
+    enableRowGroup: true
     name: Stage
```
